eLibrary/book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns =[
	#index
	path('index/',views.IndexView.as_view(), name ='index'),
	#book/1
	path('<int:pk>',views.BookDetails.as_view(), name ='book_details'),
	#book/add
	path('book/add',views.AddBook.as_view(), name ='book-add'),
		#book/delete
	path('book/<int:pk>/delete/',views.DeleteBook.as_view(), name ='book-delete'),
		#book/delete
	path('book/<int:pk>/update/',views.UpdateBook.as_view(), name ='book-update'),
	#books/register
	path('',views.Register.as_view(), name ='register'),
	path('login/',views.Login, name ='login'),


	
]

eLibrary/eLibrary/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include('book.urls')),
    path('', include('book.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root =settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

eLibrary/book/models.py
from django.db import models


# Create your models here.
class Book(models.Model):
	book_title = models.CharField(max_length =250)
	book_author = models.CharField(max_length=250)
	book_publisher = models.CharField(max_length =300)
	book_image = models.FileField()



	def __str__(self):
		return self.book_name+'-'+self.book_author

eLibrary/book/forms.py
from django.contrib.auth.models import  User
from django import forms


class  UserForm(forms.ModelForm):
	password = forms.CharField(widget = forms.PasswordInput)
	conpassword = forms.CharField(widget = forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username', 'email' , 'password']

	def clean(self):
		cleaned_data = super(UserForm,self).clean()
		password = cleaned_data.get("password")
		conpassword = cleaned_data.get("conpassword")
		msg = "did not match"
		if password != confirm_password:
			self.add_error('conpassword', msg)
            

eLibrary/book/views.py
from django.shortcuts import render,redirect
from  django.views import generic
from .models import Book
from django.contrib import messages
from django.urls import reverse_lazy
from  django.views.generic.edit import CreateView,DeleteView,UpdateView
from django.db.models.query import Q
from django.contrib.auth.models import User,auth
from django.views.generic import View
from .forms import UserForm
from django.contrib.auth import authenticate, login
# Create your views here.

class IndexView(generic.ListView):
	template_name = 'book/index.html'
	context_object_name = 'all_books'

	def get_queryset(self):
		request = self.request
		query = request.GET.get('q')
		if query is not  None:
			return Book.objects.filter(Q(book_author__icontains =query)  | Q(book_title__icontains =query) | Q(book_publisher__icontains =query))
		return Book.objects.all()

class BookDetails(generic.DetailView):
	book = Book
	template_name='book/book_details.html'
	def get_queryset(self):
		return Book.objects.all()


class AddBook(CreateView):
	model = Book
	fields = ['book_title', 'book_author' , 'book_publisher' , 'book_image']
	success_url =reverse_lazy('book:index')

class DeleteBook(DeleteView):
	model = Book
	success_url =reverse_lazy('book:index')

class UpdateBook(UpdateView):
	model = Book
	fields = ['book_title', 'book_author' , 'book_publisher' , 'book_image' ]
	success_url =reverse_lazy('book:index')

class Register(View):
	form_class = UserForm
	template_name = 'book/register.html'

	#blank form
	def get(self,request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form': form})

	#process from data
	def post(self,request):
		form = self.form_class(request.POST)

		if form.is_valid():
			user = form.save(commit= False)

			#cleaned/normalizeed data
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()

			#login
			user = authenticate(username =username, password =password)

			if user is not None:
				if user.is_active:

					login(request,user)
					return redirect('book:index')
		return render(request, self.template_name, {'form': form})



def Login(request):
	template_name = 'book/login.html'
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']

		user = auth.authenticate(username=username, password= password)

		if user is not None:
			auth.login(request,user)
			return redirect('book:index')
		else:
			messages.info(request,'invalid')
	else:
		return render(request,template_name)





eLibrary/book/templates/book/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}Library Home{% endblock %}</title>
	{% load static %}

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
	<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target ="#topNavBar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span> 
			</button>
			<a class="navbar-brand" href="{% url 'book:index' %}">eLibrary</a>
			
		</div>

		<div class="collapse navbar-collapse" id="topNavBar">
			<ul class="nav navbar-nav">
				<li class="active">
					<a href="{% url 'book:index' %}">
						<span class="glyphicon glyphicon-book"
						area-hidden ="true"></span>&nbsp;
						Books
					</a>
				</li>
			</ul>
			<form class="navbar-form navbar-left" role="search" method="get" action="">
				<div class="from-group">
					<input type="text" name="q" id="search_name" placeholder="Search Book" value="{{request.GET.q}}">
					<button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search" ></span></button>
				</div>
			</form>
			<ul class="nav navbar-nav navbar-right">
				<li class="">
					<a href="{% url 'book:book-add' %}">
						<span class="glyphicon glyphicon-plus"
						area-hidden ="true"></span>&nbsp;
						Add Books
					</a>
				</li>
				<li class="">
					<a href="#">
						<span class="glyphicon glyphicon-off"
						area-hidden ="true"></span>&nbsp;
						Logout
					</a>
				</li>
			</ul>
		</div>
		
	</div>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

eLibrary/book/templates/book/book_details.html
{% extends 'book/base.html' %}
{% block title %}Book Details{% endblock %}
{% block body %}

<h1>Book Details</h1>

<div class="row">
	<div class="col-sm-12">
		<div class="col-sm-6">
			<img src="{{book.book_image.url}}" width="400" height="500">
			<h1>Title-{{book.book_title}}</h1>
			<h3>Author-{{book.book_author}}</h3>
			<h5>Publication-{{book.book_publisher}}</h5>

		</div>
	</div>

</div>



{% endblock %}

eLibrary/book/templates/book/book_form.html
{% extends 'book/base.html' %}
{% block title %}Add Books{% endblock %}
{% block body %}
<div class="container-fluid">

	<div class="row">
		<div class="col-sm-12 col-md-7">
			<div class="panel-body">
				<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					{% include 'book/form_template.html' %}
					<div class="form-group">
						<div class="col-sm-offset-2 col-md-10">
							<button type="submit" class="btn btn-success">Submit</button>
						</div>
					</div>

					
				</form>
					
				
			</div>
			
		</div>
		
	</div>
</div>

{% endblock %}

eLibrary/book/templates/book/form_template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-md-10">
			<span class="text-danger small">{{field.errors}}</span>
		</div>
		<label class="control-label col-sm-2">
			{{field.label_tag}}
		</label>
		<div class="col-sm-10">{{field}}</div>
		
	</div>

{% endfor %}

eLibrary/book/templates/book/index.html
{% extends 'book/base.html' %}
{% block body %}
	<h1>All the books</h1>
	<div class="row">
		<div class="col-sm-12">
			<ul style="list-style: none;">
				
			{% for book in all_books %}
			<li>
				<div class="col-sm-4">
					<img src="{{book.book_image.url}}" width="300" height="400"><br>
			    	<label style="font-size: large;">{{book.book_title}}</label><br>
			        <label style="font-size: small;">{{book.book_author}}</label><br>
					<a href="{% url 'book:book_details' book.id %}">
			        <button type="button" class="btn btn-primary"> Details </button>
			        </a>
			        <form action="{% url 'book:book-update' book.id %}" style="display: inline;">
			        {% csrf_token %}
			        <input type="hidden" name="book_id" value="{{ book.id }}">
			        <button style=""> <span class="glyphicon glyphicon-pencil"
					area-hidden ="true"></span></button>
					</form>
					<form action="{% url 'book:book-delete' book.id %}" method="post" style="display: inline;">
			        {% csrf_token %}
			        <input type="hidden" name="book_id" value="{{ book.id }}">
			        <button style=""> <span class="glyphicon glyphicon-trash"
						area-hidden ="true"></span></button>
					</form>
		        </div>
			</li>
			{% endfor %}
			
			
		</ul> 	
	</div>
		</div>
{% endblock %}

eLibrary/book/templates/book/login.html
{% extends 'book/base.html' %}
{% block title %}Register{% endblock %}


{% block body %}

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12">
			<h5>Login!!</h5>
			{% if error_message %}
				<p>
				<strong>{{error_message}}</strong>
				</p>
			{% endif %}
				<form action="{% url 'book:login' %}" method="post">
					{% csrf_token %}
				  <div class="form-group">
				    <label >User Name</label>
				    <input type="text" name="username" class="form-control" id="username"  placeholder="Enter username">
				  </div>
				  <div class="form-group">
				    <label >Password</label>
				    <input type="password" name="password" class="form-control" id="password" placeholder="Password">
				  </div>
				  <button type="submit" class="btn btn-primary">Submit</button>
				</form>


				  <a href="{% url 'book:register' %}">
				<h5 style="color: red">Go to Registration form</h5>
				  </a>
				
		</div>
		
	</div>
	
</div>
{% endblock%}



eLibrary/book/templates/book/register.html
{% extends 'book/base.html' %}
{% block title %}Register{% endblock %}


{% block body %}

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12">
			<h5>Create New Account Here!</h5>
			{% if error_message %}
				<p>
				<strong>{{error_message}}</strong>
				</p>
			{% endif %}
				<form action="{% url 'book:register' %}" method="post">
					{% csrf_token %}
				  <div class="form-group">
				    <label >User Name</label>
				    <input type="text" class="form-control" id="first_name" name="username"  placeholder="User Name">
				  </div> 
				  <div class="form-group">
				    <label >Email address</label>
				    <input type="email" name="email"  class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email">
				    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
				  </div>
				  <div class="form-group">
				    <label >Password</label>
				    <input type="password" name="password"  class="form-control" id="password" placeholder="Password">
				  </div>
				  <div class="form-group">
				    <label >Password</label>
				    <input type="password" name="conpassword"  class="form-control" id="conpassword" placeholder="Confirm Password">
				  </div>
				  <button type="submit" class="btn btn-primary">Submit</button>

				  
				
				</form>

				  <a href="{% url 'book:login' %}">
				<h5 style="color: red">Already have an account???</h5>
				  </a>
		</div>
		
	</div>
	
</div>



{% endblock %}